ADRAR: [corn, wheat]
CHLEF: [tomatoes, carrot, onion,lemons]
LAGHOUAT: [dates, wheat,olives]
O.E.BOUAGHI: [corn, carrot, onion]
BATNA: [dates,apple,olives]
BEJAIA: []
BISKRA: [tomatoes, green pepper, dates, wheat, aubergine,olives]
BECHAR: []
BLIDA: [Potatoes, green pepper, wheat, aubergine,lemons,apple,olives]
BOUIRA: [Potatoes,wheat]
TAMANRASSET: []
TEBESSA: [Potatoes, dates]
TLEMCEN: [tomatoes,lemons,olives]
TIARET: [Potatoes, onion, aubergine]
TIZI-OUZOU: [lemons,apple]
ALGER: [Potatoes, tomatoes, carrot,lemons,apple]
DJELFA: [dates, onion]
JIJEL: [tomatoes, green pepper, corn, onion,olives]
SETIF: [green pepper]
SAIDA: [carrot, onion, aubergine]
SKIKDA: [corn, carrot]
S.B.ABBES: [corn,olives]
ANNABA: [Potatoes, wheat,lemons]
GUELMA: [wheat, carrot]
CONSTANTINE: [wheat,apple]
MEDEA: [apple]
MOSTAGANEM: [tomatoes, green pepper, carrot, onion, aubergine,lemons,olives]
M'SILA: [green pepper, carrot, aubergine]
MASCARA: [onion,olives]
OUARGLA: [green pepper,wheat,dates]
ORAN: []
EL-BAYADH: [corn, dates, onion, aubergine]
ILLIZI: []
B.B.ARRERIDJ: []
BOUMERDES: [,apple]
EL-TARF: [Potatoes,lemons]
TINDOUF: [tomatoes, green pepper, aubergine]
TISSEMSILT: []
EL-OUED: [Potatoes, tomatoes, green pepper, dates]
KHENCHELA: [dates, aubergine,apple]
SOUK-AHRAS: []
TIPAZA: [tomatoes, green pepper, carrot,lemons,apple]
MILA: [Potatoes, wheat, carrot, aubergine]
AIN-DEFLA: [Potatoes, tomatoes, onion,apple]
NAAMA: []
A.TEMOUCHENT: []
GHARDAIA: [dates]
RELIZANE: [lemons,olives]