ACTIONS = [
['ADRAR', 'Wheat', 'above average', 0.5] ,
['ADRAR', 'Wheat', 'ideal', 0.5] ,
['ADRAR', 'Corn', 'above average', 0.5] ,
['ADRAR', 'Corn', 'ideal', 0.5] ,
['CHLEF', 'Wheat', 'above average', 0.5] ,
['CHLEF', 'Wheat', 'ideal', 0.5] ,
['CHLEF', 'Corn', 'above average', 0.5] ,
['CHLEF', 'Corn', 'ideal', 0.5] ,
['LAGHOUAT', 'Wheat', 'above average', 0.5] ,
['LAGHOUAT', 'Wheat', 'ideal', 0.5] ,
['LAGHOUAT', 'Corn', 'above average', 0.5] ,
['LAGHOUAT', 'Corn', 'ideal', 0.5] ,
['O.E.BOUAGHI', 'Wheat', 'above average', 0.5] ,
['O.E.BOUAGHI', 'Wheat', 'ideal', 0.5] ,
['O.E.BOUAGHI', 'Corn', 'above average', 0.5] ,
['O.E.BOUAGHI', 'Corn', 'ideal', 0.5] ,
['BATNA', 'Wheat', 'above average', 0.5] ,
['BATNA', 'Wheat', 'ideal', 0.5] ,
['BATNA', 'Corn', 'above average', 0.5] ,
['BATNA', 'Corn', 'ideal', 0.5] ,
['BEJAIA', 'Wheat', 'above average', 0.5] ,
['BEJAIA', 'Wheat', 'ideal', 0.5] ,
['BEJAIA', 'Corn', 'above average', 0.5] ,
['BEJAIA', 'Corn', 'ideal', 0.5] ,
['BISKRA', 'Wheat', 'above average', 0.5] ,
['BISKRA', 'Wheat', 'ideal', 0.5] ,
['BISKRA', 'Corn', 'above average', 0.5] ,
['BISKRA', 'Corn', 'ideal', 0.5] ,
['BECHAR', 'Wheat', 'above average', 0.5] ,
['BECHAR', 'Wheat', 'ideal', 0.5] ,
['BECHAR', 'Corn', 'above average', 0.5] ,
['BECHAR', 'Corn', 'ideal', 0.5] ,
['BLIDA', 'Wheat', 'above average', 0.5] ,
['BLIDA', 'Wheat', 'ideal', 0.5] ,
['BLIDA', 'Corn', 'above average', 0.5] ,
['BLIDA', 'Corn', 'ideal', 0.5] ,
['BOUIRA', 'Wheat', 'above average', 0.5] ,
['BOUIRA', 'Wheat', 'ideal', 0.5] ,
['BOUIRA', 'Corn', 'above average', 0.5] ,
['BOUIRA', 'Corn', 'ideal', 0.5] ,
['TAMANRASSET', 'Wheat', 'above average', 0.5] ,
['TAMANRASSET', 'Wheat', 'ideal', 0.5] ,
['TAMANRASSET', 'Corn', 'above average', 0.5] ,
['TAMANRASSET', 'Corn', 'ideal', 0.5] ,
['TEBESSA', 'Wheat', 'above average', 0.5] ,
['TEBESSA', 'Wheat', 'ideal', 0.5] ,
['TEBESSA', 'Corn', 'above average', 0.5] ,
['TEBESSA', 'Corn', 'ideal', 0.5] ,
['TLEMCEN', 'Wheat', 'above average', 0.5] ,
['TLEMCEN', 'Wheat', 'ideal', 0.5] ,
['TLEMCEN', 'Corn', 'above average', 0.5] ,
['TLEMCEN', 'Corn', 'ideal', 0.5] ,
['TIARET', 'Wheat', 'above average', 0.5] ,
['TIARET', 'Wheat', 'ideal', 0.5] ,
['TIARET', 'Corn', 'above average', 0.5] ,
['TIARET', 'Corn', 'ideal', 0.5] ,
['TIZI-OUZOU', 'Wheat', 'above average', 0.5] ,
['TIZI-OUZOU', 'Wheat', 'ideal', 0.5] ,
['TIZI-OUZOU', 'Corn', 'above average', 0.5] ,
['TIZI-OUZOU', 'Corn', 'ideal', 0.5] ,
['ALGER', 'Wheat', 'above average', 0.5] ,
['ALGER', 'Wheat', 'ideal', 0.5] ,
['ALGER', 'Corn', 'above average', 0.5] ,
['ALGER', 'Corn', 'ideal', 0.5] ,
['DJELFA', 'Wheat', 'above average', 0.5] ,
['DJELFA', 'Wheat', 'ideal', 0.5] ,
['DJELFA', 'Corn', 'above average', 0.5] ,
['DJELFA', 'Corn', 'ideal', 0.5] ,
['JIJEL', 'Wheat', 'above average', 0.5] ,
['JIJEL', 'Wheat', 'ideal', 0.5] ,
['JIJEL', 'Corn', 'above average', 0.5] ,
['JIJEL', 'Corn', 'ideal', 0.5] ,
['SETIF', 'Wheat', 'above average', 0.5] ,
['SETIF', 'Wheat', 'ideal', 0.5] ,
['SETIF', 'Corn', 'above average', 0.5] ,
['SETIF', 'Corn', 'ideal', 0.5] ,
['SAIDA', 'Wheat', 'above average', 0.5] ,
['SAIDA', 'Wheat', 'ideal', 0.5] ,
['SAIDA', 'Corn', 'above average', 0.5] ,
['SAIDA', 'Corn', 'ideal', 0.5] ,
['SKIKDA', 'Wheat', 'above average', 0.5] ,
['SKIKDA', 'Wheat', 'ideal', 0.5] ,
['SKIKDA', 'Corn', 'above average', 0.5] ,
['SKIKDA', 'Corn', 'ideal', 0.5] ,
['S.B.ABBES', 'Wheat', 'above average', 0.5] ,
['S.B.ABBES', 'Wheat', 'ideal', 0.5] ,
['S.B.ABBES', 'Corn', 'above average', 0.5] ,
['S.B.ABBES', 'Corn', 'ideal', 0.5] ,
['ANNABA', 'Wheat', 'above average', 0.5] ,
['ANNABA', 'Wheat', 'ideal', 0.5] ,
['ANNABA', 'Corn', 'above average', 0.5] ,
['ANNABA', 'Corn', 'ideal', 0.5] ,
['GUELMA', 'Wheat', 'above average', 0.5] ,
['GUELMA', 'Wheat', 'ideal', 0.5] ,
['GUELMA', 'Corn', 'above average', 0.5] ,
['GUELMA', 'Corn', 'ideal', 0.5] ,
['CONSTANTINE', 'Wheat', 'above average', 0.5] ,
['CONSTANTINE', 'Wheat', 'ideal', 0.5] ,
['CONSTANTINE', 'Corn', 'above average', 0.5] ,
['CONSTANTINE', 'Corn', 'ideal', 0.5] ,
['MEDEA', 'Wheat', 'above average', 0.5] ,
['MEDEA', 'Wheat', 'ideal', 0.5] ,
['MEDEA', 'Corn', 'above average', 0.5] ,
['MEDEA', 'Corn', 'ideal', 0.5] ,
['MOSTAGANEM', 'Wheat', 'above average', 0.5] ,
['MOSTAGANEM', 'Wheat', 'ideal', 0.5] ,
['MOSTAGANEM', 'Corn', 'above average', 0.5] ,
['MOSTAGANEM', 'Corn', 'ideal', 0.5] ,
['MSILA', 'Wheat', 'above average', 0.5] ,
['MSILA', 'Wheat', 'ideal', 0.5] ,
['MSILA', 'Corn', 'above average', 0.5] ,
['MSILA', 'Corn', 'ideal', 0.5] ,
['MASCARA', 'Wheat', 'above average', 0.5] ,
['MASCARA', 'Wheat', 'ideal', 0.5] ,
['MASCARA', 'Corn', 'above average', 0.5] ,
['MASCARA', 'Corn', 'ideal', 0.5] ,
['OUARGLA', 'Wheat', 'above average', 0.5] ,
['OUARGLA', 'Wheat', 'ideal', 0.5] ,
['OUARGLA', 'Corn', 'above average', 0.5] ,
['OUARGLA', 'Corn', 'ideal', 0.5] ,
['ORAN', 'Wheat', 'above average', 0.5] ,
['ORAN', 'Wheat', 'ideal', 0.5] ,
['ORAN', 'Corn', 'above average', 0.5] ,
['ORAN', 'Corn', 'ideal', 0.5] ,
['EL-BAYADH', 'Wheat', 'above average', 0.5] ,
['EL-BAYADH', 'Wheat', 'ideal', 0.5] ,
['EL-BAYADH', 'Corn', 'above average', 0.5] ,
['EL-BAYADH', 'Corn', 'ideal', 0.5] ,
['ILLIZI', 'Wheat', 'above average', 0.5] ,
['ILLIZI', 'Wheat', 'ideal', 0.5] ,
['ILLIZI', 'Corn', 'above average', 0.5] ,
['ILLIZI', 'Corn', 'ideal', 0.5] ,
['B.B.ARRERIDJ', 'Wheat', 'above average', 0.5] ,
['B.B.ARRERIDJ', 'Wheat', 'ideal', 0.5] ,
['B.B.ARRERIDJ', 'Corn', 'above average', 0.5] ,
['B.B.ARRERIDJ', 'Corn', 'ideal', 0.5] ,
['BOUMERDES', 'Wheat', 'above average', 0.5] ,
['BOUMERDES', 'Wheat', 'ideal', 0.5] ,
['BOUMERDES', 'Corn', 'above average', 0.5] ,
['BOUMERDES', 'Corn', 'ideal', 0.5] ,
['EL-TARF', 'Wheat', 'above average', 0.5] ,
['EL-TARF', 'Wheat', 'ideal', 0.5] ,
['EL-TARF', 'Corn', 'above average', 0.5] ,
['EL-TARF', 'Corn', 'ideal', 0.5] ,
['TINDOUF', 'Wheat', 'above average', 0.5] ,
['TINDOUF', 'Wheat', 'ideal', 0.5] ,
['TINDOUF', 'Corn', 'above average', 0.5] ,
['TINDOUF', 'Corn', 'ideal', 0.5] ,
['TISSEMSILT', 'Wheat', 'above average', 0.5] ,
['TISSEMSILT', 'Wheat', 'ideal', 0.5] ,
['TISSEMSILT', 'Corn', 'above average', 0.5] ,
['TISSEMSILT', 'Corn', 'ideal', 0.5] ,
['EL-OUED', 'Wheat', 'above average', 0.5] ,
['EL-OUED', 'Wheat', 'ideal', 0.5] ,
['EL-OUED', 'Corn', 'above average', 0.5] ,
['EL-OUED', 'Corn', 'ideal', 0.5] ,
['KHENCHELA', 'Wheat', 'above average', 0.5] ,
['KHENCHELA', 'Wheat', 'ideal', 0.5] ,
['KHENCHELA', 'Corn', 'above average', 0.5] ,
['KHENCHELA', 'Corn', 'ideal', 0.5] ,
['SOUK-AHRAS', 'Wheat', 'above average', 0.5] ,
['SOUK-AHRAS', 'Wheat', 'ideal', 0.5] ,
['SOUK-AHRAS', 'Corn', 'above average', 0.5] ,
['SOUK-AHRAS', 'Corn', 'ideal', 0.5] ,
['TIPAZA', 'Wheat', 'above average', 0.5] ,
['TIPAZA', 'Wheat', 'ideal', 0.5] ,
['TIPAZA', 'Corn', 'above average', 0.5] ,
['TIPAZA', 'Corn', 'ideal', 0.5] ,
['MILA', 'Wheat', 'above average', 0.5] ,
['MILA', 'Wheat', 'ideal', 0.5] ,
['MILA', 'Corn', 'above average', 0.5] ,
['MILA', 'Corn', 'ideal', 0.5] ,
['AIN-DEFLA', 'Wheat', 'above average', 0.5] ,
['AIN-DEFLA', 'Wheat', 'ideal', 0.5] ,
['AIN-DEFLA', 'Corn', 'above average', 0.5] ,
['AIN-DEFLA', 'Corn', 'ideal', 0.5] ,
['NAAMA', 'Wheat', 'above average', 0.5] ,
['NAAMA', 'Wheat', 'ideal', 0.5] ,
['NAAMA', 'Corn', 'above average', 0.5] ,
['NAAMA', 'Corn', 'ideal', 0.5] ,
['A.TEMOUCHENT', 'Wheat', 'above average', 0.5] ,
['A.TEMOUCHENT', 'Wheat', 'ideal', 0.5] ,
['A.TEMOUCHENT', 'Corn', 'above average', 0.5] ,
['A.TEMOUCHENT', 'Corn', 'ideal', 0.5] ,
['GHARDAIA', 'Wheat', 'above average', 0.5] ,
['GHARDAIA', 'Wheat', 'ideal', 0.5] ,
['GHARDAIA', 'Corn', 'above average', 0.5] ,
['GHARDAIA', 'Corn', 'ideal', 0.5] ,
['RELIZANE', 'Wheat', 'above average', 0.5] ,
['RELIZANE', 'Wheat', 'ideal', 0.5] ,
['RELIZANE', 'Corn', 'above average', 0.5] ,
['RELIZANE', 'Corn', 'ideal', 0.5] ,
]